package iptables

import (
	"reflect"
	"testing"
)

func TestParseDeleteCmds(t *testing.T) {
	save := `# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ELEUTHERIOS_DNS - [0:0]
-A PREROUTING -i br0 -j ELEUTHERIOS_DNS
-A PREROUTING -i br1 -j ELEUTHERIOS_DNS
-A PREROUTING -i br0 -j SOMETHING_ELSE
-A ELEUTHERIOS_DNS -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:9753
COMMIT
`
	got := parseDeleteCmds(save, "nat", "PREROUTING", "ELEUTHERIOS_DNS")
	want := [][]string{
		{"-t", "nat", "-D", "PREROUTING", "-i", "br0", "-j", "ELEUTHERIOS_DNS"},
		{"-t", "nat", "-D", "PREROUTING", "-i", "br1", "-j", "ELEUTHERIOS_DNS"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("parseDeleteCmds:\n got  %v\n want %v", got, want)
	}
}

func TestParseDeleteCmdsNoMatch(t *testing.T) {
	save := `-A PREROUTING -i br0 -j MASQUERADE
-A INPUT -i lo -j ACCEPT
`
	got := parseDeleteCmds(save, "nat", "PREROUTING", "ELEUTHERIOS_DNS")
	if len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestParseDeleteCmdsEmpty(t *testing.T) {
	got := parseDeleteCmds("", "nat", "PREROUTING", "ELEUTHERIOS_DNS")
	if len(got) != 0 {
		t.Errorf("expected empty for empty input, got %v", got)
	}
}

func TestHasJump(t *testing.T) {
	tests := []struct {
		fields []string
		target string
		want   bool
	}{
		{[]string{"-A", "PREROUTING", "-i", "br0", "-j", "ELEUTHERIOS_DNS"}, "ELEUTHERIOS_DNS", true},
		{[]string{"-A", "PREROUTING", "-i", "br0", "-j", "OTHER"}, "ELEUTHERIOS_DNS", false},
		{[]string{"-A", "PREROUTING", "-i", "br0"}, "ELEUTHERIOS_DNS", false},
		{[]string{}, "X", false},
	}
	for _, tt := range tests {
		got := hasJump(tt.fields, tt.target)
		if got != tt.want {
			t.Errorf("hasJump(%v, %q) = %v, want %v", tt.fields, tt.target, got, tt.want)
		}
	}
}
